runtime: nodejs14

service: default
env: standard
instance_class: F1
default_expiration: "7d 0h"

handlers:
  - url: /static
    static_dir: dist/build/static
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
